platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: latest

inputs:
  - name: redis-demo-repo

outputs:
  - name: jar-file
    path: target

run: 
  path: sh
  args: 
    - -exc
    - |
      mvn -f redis-demo-repo/pom.xml -DskipTests=true package
      cp redis-demo-repo/target/redis-demo-bittrex-0.0.1-SNAPSHOT.jar target/

#run:
#  path: mvn
#  args: ["-f", "redis-demo-repo/pom.xml", "-DskipTests=true", "package"]


