resources:
- name: redis-demo-repo
  type: git
  source:
    uri: https://github.com/agregory999/redis-demo-bittrex
- name: resource-deploy-web-app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:
  - name: maven-package
    serial: true
    plan:
    - get: redis-demo-repo
      trigger: true
    - task: maven-package
      privileged: true
      file: redis-demo-repo/build.yml
    - put: resource-deploy-web-app 
      params:
        manifest: redis-demo-repo/manifest.yml
        path: jar-file/redis-demo-bittrex-0.0.1-SNAPSHOT.jar
